dist: trusty
language: java

notifications:
  email: false

install:
- sudo apt-get update
- sudo apt-get install --no-install-recommends texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended texlive-lang-german texlive-generic-extra

script:
- test `find . -not -type d -exec file "{}" ";" | grep CRLF | wc -l` -eq 0
- cd src
- mvn -U -B test
- cd ..
- git fetch origin master
- git diff --name-only FETCH_HEAD | { grep "\.java" || true; }
- git diff --name-only FETCH_HEAD | grep "\.java" | xargs -r java -jar tools/checkstyle-7.4-all.jar -c src/checkstyle.xml
- git diff --name-only FETCH_HEAD | grep "\.java" | xargs -r java -jar tools/checkstyle-7.4-all.jar -c src/checkstyle.xml | wc -l | xargs test 2 -ge
- cd docs
- export max_print_line=200
- pdflatex -interaction=batchmode Pflichtenheft &> /dev/null
- cat Pflichtenheft.log | grep -C 15 -i ERROR
- pdflatex -interaction=batchmode Design &> /dev/null
- cat Design.log | grep -C 15 -i ERROR
